version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: gestor_eventos_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: GestorEventosDeportivos
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: